export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const VOTE_SUCCESS = 'VOTE_SUCCESS'
